name: Build
on: [ push, pull_request ]
jobs:
  build-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:

      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.*

      - name: Checkout Project
        uses: actions/checkout@v4.2.2
      
      - name: Remove Broken Submodules
        run: |
          git submodule deinit -f modules/FFmpeg
          git submodule deinit -f modules/libpng
          git submodule deinit -f modules/openssl
          git submodule deinit -f modules/x246
          git submodule deinit -f modules/zlib

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0