name: Build
on: [ push, pull_request ]
jobs:
  build-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-13, macos-14]
    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Project
        if: ${{ ! startsWith( matrix.os, 'windows' ) }}
        uses: actions/checkout@v4.2.2
      
      - name: Checkout Project on Windows
        if: ${{ startsWith( matrix.os, 'windows' ) }}
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Setup Fortran
        if: ${{ ! startsWith( matrix.os, 'windows' ) }}
        uses: fortran-lang/setup-fortran@v1

      - name: Setup Fortran on Windows
        if: ${{ startsWith( matrix.os, 'windows' ) }}
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: 'intel'

      - name: Install Qt
        if: ${{ ! startsWith( matrix.os, 'macos' ) }}
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.*
      
      - name: Install Dependencies on Ubuntu
        if: ${{ startsWith( matrix.os, 'ubuntu' ) }}
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev -y
          sudo apt-get install librust-bzip2-dev -y
          sudo apt-get install liblzma-dev -y
          sudo apt-get install libb2-dev -y
          sudo apt-get install libssh2-1-dev -y
          sudo apt-get install libqglviewer-dev-qt5 -y
          sudo apt-get install libopenmesh-dev -y
          sudo apt-get install libyaml-cpp-dev -y
          sudo apt-get install libopenbabel-dev -y
          sudo apt-get install libboost-iostreams-dev libboost-serialization-dev -y
          sudo ln -s /usr/include/openbabel3/openbabel /usr/include/
          git submodule update --init modules/libQGLViewer
      
      - name: Install Dependencies on MacOS
        if: ${{ startsWith( matrix.os, 'macos' ) }}
        run: |
          brew install boost
          brew install icu4c
          brew install libarchive
          brew install libssh2
          brew install open-babel
          brew install qt@5
          brew install open-mesh
          brew install yaml-cpp
          brew link open-babel
          brew link icu4c
          git submodule update --init modules/libQGLViewer
      
      - name: Install boost on Windows
        if: ${{ startsWith( matrix.os, 'windows' ) }}
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.73.0

      - name: Build Project on Ubuntu
        if: ${{ startsWith( matrix.os, 'ubuntu' ) }}
        run: |
          cmake -B build
          cmake --build build -j2

      - name: Build Project on Windows
        if: ${{ startsWith( matrix.os, 'windows' ) }}
        uses: threeal/cmake-action@v2.1.0

      - name: Build Project on MacOS 13
        if: ${{ matrix.os == 'macos-13' }}
        env:
          Qt5_DIR: /usr/local/opt/qt@5
        run: |
          ls -l /usr/local/opt
          ls -l /usr/local/opt/include/openbabel3 || true
          sudo ln -s /usr/local/opt/include/openbabel3/openbabel /usr/local/opt/include/
          cmake -B build
          cmake --build build

      - name: Build Project on MacOS 14
        if: ${{ matrix.os == 'macos-14' }}
        env:
          Qt5_DIR: /opt/homebrew/opt/qt@5
        run: |
          sudo ln -s /opt/homebrew/include/openbabel3/openbabel /opt/homebrew/include/
          ls -l /opt/homebrew/lib/ 
          cmake -B build
          cmake --build build