name: Build
on: [ push, pull_request ]
jobs:
  build-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Project
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/checkout@v4.2.2
      
      - name: Checkout Project on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Setup Fortran
        if: ${{ matrix.os != 'windows-latest' }}
        uses: fortran-lang/setup-fortran@v1

      - name: Setup Fortran on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ls -R C:\msys64
          C:\msys64\usr\bin\pacman -S mingw-w64-lfortran

      - name: Install Qt
        if: ${{ matrix.os != 'macos-latest' }}
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.*
      
      - name: Install Dependencies on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev -y
          sudo apt-get install librust-bzip2-dev -y
          sudo apt-get install liblzma-dev -y
          sudo apt-get install libb2-dev -y
          sudo apt-get install libssh2-1-dev -y
          # sudo apt-get install libqglviewer-headers libqglviewer-dev-qt5 -y
          sudo apt-get install libqglviewer-dev-qt5 -y
          sudo apt-get install libopenmesh-dev -y
          sudo apt-get install libyaml-cpp-dev -y
          sudo apt-get install libopenbabel-dev -y
          sudo apt-get install libboost-iostreams-dev libboost-serialization-dev -y
      
      - name: Install Dependencies on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install boost
          brew install libarchive
          brew install libssh2
          brew install open-babel
          brew install qt@5
          brew install open-mesh
          brew install yaml-cpp
      
      - name: Install boost on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: MarkusJx/install-boost@v2
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.73.0

      - name: Build Project on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo ln -s /usr/include/openbabel3/openbabel /usr/include/
          git submodule update modules/libQGLViewer
          rm -rf build
          cmake -B build
          cmake --build build

      - name: Build Project on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        uses: threeal/cmake-action@v2.1.0

      - name: Build Project on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          Qt5_DIR: /opt/homebrew/opt/qt@5
        run: |
          git submodule update modules/libQGLViewer
          rm -rf build
          cmake -B build
          cmake --build build